# Generated by Django 3.2 on 2022-11-11 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('blood_group', models.CharField(max_length=500)),
                ('last_donate_date', models.DateField(max_length=264, unique=True)),
                ('disease', models.CharField(max_length=500)),
                ('quantity', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reg_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('blood_group', models.CharField(max_length=500)),
                ('disease', models.CharField(max_length=500)),
                ('profile_photo', models.ImageField(upload_to='images/')),
                ('status', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('blood_group', models.CharField(max_length=500)),
                ('profile_photo', models.ImageField(upload_to='images/')),
                ('status', models.CharField(max_length=10)),
                ('last_donate_date', models.DateField(max_length=264, unique=True)),
                ('role', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
